pipeline {
    agent any
    stages {
        stage ("Fetching.....") {
            steps {
                echo "========Fetching========"
            }
        }
    
        stage ("Building.....") {
            steps {
                echo "=======Building========"            
            }
                    
        }
        stage ("Testing.....") {
            steps {
                echo "=======Testing========"
            }
        }
        stage ("Deploying.....") {
            steps {
                echo "=======Deploying========"
            }
        }
    }
}