pipeline{
    agent any
    stages{
        stage("Fetching.....") {
            steps {
                    sh 'echo "========Fetching========"'
            }
        }
    }
        stage("Building.....") {
            steps {
                sh 'echo "=======Building========"'            
            }
                    
        }
        stage("Testing.....") {
            steps {
                sh 'echo "=======Testing========"'
            }
        }
        stage("Deploying.....") {
            steps {
                sh 'echo "=======Testing========"'
            }
        }
    }